export const GENERATE_STARTED = 'GENERATE_STARTED';
export const GENERATE_FINISHED = 'GENERATE_FINISHED';
export const ADD_ARRAY_ITEM = 'ADD_ARRAY_ITEM';
export const DELETE_ARRAY_ITEM = 'DELETE_ARRAY_ITEM';
export const CHANGE_ARRAY_ITEM = 'CHANGE_ARRAY_ITEM';